# Process Lambdin Cards for Anki

In [1]:
import datetime as dt
import hashlib
import os
import pandas as pd

In [2]:
MAX_VOCAB_LESSON = 52
MAX_GRAMMAR_PARAGRAPH = 187

In [3]:
PATH_TO_FILES = '/Users/gabriele/Library/Mobile Documents/com~apple~CloudDocs/Anki/'

df_vocab = pd.read_csv(os.path.join(PATH_TO_FILES, 'lambdin_vocab.csv'))
df_grammar = pd.read_csv(os.path.join(PATH_TO_FILES, 'lambdin_grammar.csv'))

In [4]:
df_vocab = df_vocab.loc[df_vocab['lesson'] <= MAX_VOCAB_LESSON].copy()
df_vocab['lesson'] = df_vocab['lesson'].astype(int)

In [5]:
df_vocab.sample(n=5)

,hebrew,remarks_hebrew,english,remarks_english,part_of_speech,lesson
52,לְ,NaN,"to, for (dative sense), as",NaN,preposition,4
144,שִׂמְחָה,NaN,joy,pl. -ôṯ,noun,12
236,אֲדָמָה,NaN,"earth, ground, soil, landed property","sometimes synonymous with אֶרֶץ, which retains...",noun,18
227,שְׁלִישִׁי,NaN,third (m.),NaN,adjective,17
756,הֵחֵל,יָחֵל,to begin,usually + complementary inf.,verb,48

In [6]:
df_grammar = df_grammar.loc[df_grammar['paragraph'] <= MAX_GRAMMAR_PARAGRAPH].copy()
df_grammar['paragraph'] = df_grammar['paragraph'].astype(int)

In [7]:
df_grammar.sample(n=5)

,prompt,remarks_prompt,answer,remarks_answer,paragraph,topic
1533,eighteen (f.),NaN,שְׁמֹנֶה עֶשְׂרֵה,NaN,164,the numbers from 11 to 19
545,their (m. pl.) brothers,אַחִים,אֲחֵיהֶם,NaN,88,"nouns פֶּה ,אָח ,אָב"
1749,(is) raising up (m. sg.),קום,מְקוֹמֵם,NaN,180,polel verb examples
855,sit! (f. sg.),ישׁב,שְׁבִי,NaN,120,"imperfect and related forms of verbs I-י, type..."
532,your (m. pl.) brother {father - mouth},אָח {אָב – פֶּה},אֲחִיכֶם,{אֲבִיכֶם – פִּיכֶם},88,"nouns פֶּה ,אָח ,אָב"

In [8]:
def create_unique_id(word):
    return hashlib.sha1(word.encode('utf-8')).hexdigest()

In [9]:
df_vocab['id'] = (df_vocab['hebrew'] + ' ' + df_vocab['lesson'].astype(str)).apply(create_unique_id)

assert df_vocab['id'].duplicated().sum() == 0

In [10]:
df_vocab['last_updated_on'] = str(dt.date.today())

In [11]:
df_grammar['id'] = (df_grammar['answer'] + ' ' + df_grammar['prompt'].astype(str)).apply(create_unique_id)

assert df_grammar['id'].duplicated().sum() == 0

In [12]:
df_grammar.loc[df_grammar['id'].duplicated()]

Empty DataFrame
Columns: [prompt, remarks_prompt, answer, remarks_answer, paragraph, topic, id]
Index: []

In [13]:
df_grammar['last_updated_on'] = str(dt.date.today())

In [14]:
df_vocab = df_vocab[['id', 'hebrew', 'remarks_hebrew', 'english', 'remarks_english',
                     'part_of_speech', 'lesson', 'last_updated_on']]

In [15]:
df_vocab.sample(n=10)

,id,hebrew,remarks_hebrew,english,remarks_english,part_of_speech,lesson,last_updated_on
256,59f5337bb28c325c49bc219800828634b3847cc6,נָחָשׁ,NaN,snake,pl. -îm,noun,19,2022-07-24
402,a9b513c3320227460e25d8100dcbe2ab08d6da2b,סָגַר,יִסְגֹּר,to close,NaN,verb,26,2022-07-24
126,87726bee764810d575a07561373ab9253e3bfa29,לָקַח,NaN,to take,NaN,verb,10,2022-07-24
634,4b1d8d4a45ba33f2f0d57bad06b8b4d954f366c3,נִחַם,יְנַחֵם,"to comfort, console",Piel,verb,42,2022-07-24
18,e46d704e21775ed9fe9d72bde3279a443fd8f38b,הֵיכָל,NaN,"palace, temple",NaN,noun,2,2022-07-24
550,375c6c3231ae955555eb1fef55ee1d3e4f16c61d,הָאֲנָשִׁים כֻּלָּם,NaN,all of the men,with כֻּלּ־,phrase,36,2022-07-24
167,87a92cbb1c5b1c63215be9457b31872dc1a4f40a,אָמָה,NaN,"maidservant, female slave",not שִׁפְחָה,noun,13,2022-07-24
442,ce7614cf61b6bff1fa340ba425a70bcb727511ab,שְׁתַּֿיִם,NaN,two (f. abs.),NaN,numeral,29,2022-07-24
341,2a988bb4b58d32df58bc4a90e055911102a8c41c,קֶֿדֶם,NaN,east,NaN,noun,23,2022-07-24
352,a1d1d53370efa8e4981088afbc90b7fc36e0729a,תֶּֿרַח,NaN,Terah,father of Abraham,proper name,23,2022-07-24

In [16]:
df_grammar.columns

Index(['prompt', 'remarks_prompt', 'answer', 'remarks_answer', 'paragraph',
       'topic', 'id', 'last_updated_on'],
      dtype='object')

In [17]:
df_grammar = df_grammar[['id', 'prompt', 'remarks_prompt', 'answer', 'remarks_answer',
                         'paragraph', 'topic','last_updated_on']]

In [18]:
df_grammar.sample(n=10)

,id,prompt,remarks_prompt,answer,remarks_answer,paragraph,topic,last_updated_on
1247,b0361e4a9d63fbfe17ab996a459286c43ceddb72,they were firm,כון,נָכֿוֹנוּ,NaN,146,niphal conjugation of hollow roots,2022-07-24
1576,885ce8b090dc3296e67b2388db413fdc726fed99,32 men (unit after the ten),NaN,שְׁלֹשִׁים וּשְׁנַֿיִם אִישׁ,NaN,167,numbers from 21 to 99,2022-07-24
66,f4333cfce0671b1a76b87537f2989df595b4c4c5,signs,אוֹת,אוֹתוֹת,NaN,34,plural of monosyllabic nouns with stem vowels ...,2022-07-24
1692,31eb1c74e8ba735982a086eff6c400ec60d0dc65,you (m. sg.) will kill yourself,קטל,תִּתְקַטֵּל,NaN,177,basic hithpael imperfect,2022-07-24
1596,b2894935b79e546e8a04f4dadf2be43e9833f3a1,let him set at rest,נוח,יָנַח,NaN,169,hiphil conjugation of hollow roots III-guttural,2022-07-24
1784,b5345ac4b13527af80d451aaa5a978424eb5a885,thousand (sg. abs.),NaN,אֶֿלֶף,NaN,182,final remarks on the numbers,2022-07-24
1688,f127d02df996ce833bd8137226c6fa2bfa19b298,you (f. pl.) killed yourselves,קטל,הִתְקַטַּלְתֶּן,NaN,177,basic hithpael perfect,2022-07-24
1654,8d6c51dd458daa9bb326c4e29d860fe20e357a87,(is) being told (m. sg.),נגד,מֻגָּד,NaN,175,hophal conjugation of roots I-נ,2022-07-24
1349,e3148efc2830e7a68fbd28c2f5f04d3b6e1e439b,(is) praising (m. sg.),הלל,מְהַלֵּל,NaN,151,piel conjugation of geminate roots,2022-07-24
1827,8d4a7cfc581681c6ae08509f2d2fd6c8b1346a39,he oppressed me,עִנָּה,עִנַּֿנִי,NaN,185,object suffixes on the perfect 3 m. sg.,2022-07-24

In [19]:
df_vocab.to_csv(os.path.join(PATH_TO_FILES, 'anki_lambdin_vocab_cards.csv'), index=False, header=False)
len(df_vocab)

844

In [20]:
df_grammar.to_csv(os.path.join(PATH_TO_FILES, 'anki_lambdin_grammar_cards.csv'), index=False, header=False)
len(df_grammar)

1889